package calebzhou.rdi.core.server.constant

object ColorConst {
    const val BLACK = "§0"
    const val DARK_BLUE = "§1"
    const val DARK_GREEN = "§2"
    const val DARK_AQUA = "§3"
    const val DARK_RED = "§4"
    const val PURPLE = "§5"
    const val ORANGE = "§6"
    const val GRAY = "§7"
    const val DARK_GRAY = "§8"
    const val INDIGO = "§9"
    const val BRIGHT_GREEN = "§a"
    const val AQUA = "§b"
    const val RED = "§c"
    const val PINK = "§d"
    const val YELLOW = "§e"
    const val GOLD = "§e"
    const val WHITE = "§f"
    const val MAGIC = "§k"
    const val BOLD = "§l"
    const val STRIKE = "§m"
    const val UNDERLINE = "§n"
    const val ITALIC = "§o"
    const val RESET = "§r"
}
